### PR TITLE
Use Generator Expressions Instead of List Comprehensions

### PR DESCRIPTION
**Pull request by citizenjosh**
Imagine that someone handed you a pile of 100 apples and then asked you to count how many of them were green without putting any of them down. You'd probably find this quite challenging and you'd struggle to hold the pile of apples at all. Now imagine someone handed you the apples one at a time and asked you to just count the green ones. This would be a much easier task.

In Python, when we use list comprehensions, it's like we've created the entire pile of apples and asked the interpreter to hold onto it. Sometimes, a better practice involves using generator expressions, which create iterators that yield objects one at a time. For large data sets, this can turn a slow, memory intensive operation into a relatively fast one.

Using generator expressions instead of list comprehensions can lead to better performance. This is especially true for functions such as `any` where it's not always necessary to evaluate the entire list before returning. For other functions such as `max` or `sum` it means that the program does not need to store the entire list in memory. These performance effects becomes more noticeable as the sizes of the lists involved grow large.

This codemod replaces the use of a list comprehension expression with a generator expression within certain function calls. Generators allow for lazy evaluation of the iterator, which can have performance benefits.

The changes from this codemod look like this:
```diff
- result = sum([x for x in range(1000)])
+ result = sum(x for x in range(1000))
```

<details>
  <summary>More reading</summary>

  * [https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-a-generator.html](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-a-generator.html)
  * [https://docs.python.org/3/glossary.html#term-generator-expression](https://docs.python.org/3/glossary.html#term-generator-expression)
  * [https://docs.python.org/3/glossary.html#term-list-comprehension](https://docs.python.org/3/glossary.html#term-list-comprehension)
</details>

Powered by: [pixeebot](https://docs.pixee.ai/) (codemod ID: [pixee:python/use-generator](https://docs.pixee.ai/codemods/python/pixee_python_use-generator))

### CODE REVIEW

**Comment by optilude** [comment]
This is clearly generated nonsense. Please don’t.

**Comment by drdavella** [comment]
Hi @optilude, thanks for the feedback!

I'm a @pixeebot maintainer and I'd love to find out what you thought was wrong with this PR. 

We generate these changes using an open-source framework called Codemodder: https://github.com/pixee/codemodder-python

The implementation for this particular fix can be found here: https://github.com/pixee/codemodder-python/blob/main/src/core_codemods/use_generator.py

The (human written!) description is here: https://github.com/pixee/codemodder-python/blob/main/src/core_codemods/docs/pixee_python_use-generator.md

I'd love to get your feedback, I promise not to be offended if there's something that you found particularly objectionable about either the change or the description 😅

**Comment by optilude** [comment]
Your PR is an essay explaining what generators are. It looks like spam. Changing list comprehensions to generators here is not an impactful change.

**Comment by drdavella** [comment]
@optilude thank you for the feedback, I appreciate it. 

It's an important part of our philosophy that we want to educate developers about the changes we make. It's hard to strike a balance between addressing experienced developers who already understand these concepts and more junior devs who may be less familiar. Obviously in this case we missed the mark.

Another important part of our philosophy is to introduce changes that we believe reflect best practices and have no obvious downside. In this particular case there's probably not a compelling performance improvement from this change but we also believe that there's no reason _not_ to accept a change like this. At least that's our goal.

I don't want you waste any more of your time but we would very much like to have the feedback of open-source maintainers like yourself. We intend for @pixeebot to remain free for OSS projects and if you were willing/able to provide additional feedback it would be very much appreciated.

Thanks again.

**Pull request closed without merging**
