### PR TITLE
Handle case where some stages are skipped for ageingwip

### PR DESCRIPTION
**Pull request by rafalotufo**
Instead of relying on the committed state to find the start date, if committed date is empty, we sort all dates and get the first one.

### CODE REVIEW

**Comment by matiasfrndz** [comment]
Hi @rafalotufo , that looks cool. I found that skipped columns also causes undesirable results in the calculation of cycle times, therefore I submitted #24 in which I try to solve both problems. What do you think?

**Comment by rlotufo** [comment]
I've tested the changes merged into master from your pull request and I've seen unexpected changes to charts like the burnup. From my analysis, the issue is the change made to cycletime.py which is a significant dependency to other charts.

If you modify the test for missing column and make the missing column the first committed step (Committed or Next), you will get incorrect results. If you make the same changes to other tests, you will find similar regressions to other calculators.

From my analysis, there were two issues with skipped columns. The first one I resolved in https://github.com/DeloitteDigitalUK/jira-agile-metrics/commit/4ac988031aa1a209ed869635fc424e03489b69d5

The second was the ageing wip issue that I tried to resolve with this pull request. I haven't seen any other issue with skipped columns other than these two.

My recommendation would be revert the last merge to accept this change request. I think it will correctly solve the missing columns issue with significantly less code changes.

**Comment by optilude** [comment]
Does that mean the  other PR, which I just merged, broke something?

**Comment by rafalotufo** [comment]
Yes. It significantly breaks things for cases in which the committed
column is skipped.

**Comment by optilude** [comment]
Okay. I'll revert it for now.

**Comment by matiasfrndz** [comment]
Thank you for the feedback @rafalotufo, I will look into it.

The reason I changed `cycletime.py` is that it too has some issues, as demonstrated in the unit test added in a964878. For me #24, or  fixed that issue as well as the regarding the ageing WiP calculation demonstrated in the new unit test added in 399f96d. For me #24, or ac64de8 specifically, fixed both issues, while all other existing tests still passed.

Could you explain how exactly I can reproduce the issues you observed?

Would it be okay to move this conversation to #24 ?

**Comment by matiasfrndz** [comment]
Hi @rlotufo, I have a comprehension question: if I understand correctly this push request has been created from you master branch and after creating the pull request, that same branch has received changes that seem unrelated. Could it be that this pull request is outdated?

**Comment by rafalotufo** [comment]
Yes, I'll close this pull request

**Pull request closed without merging**
