### PR TITLE
Throughput image size data label fix

### PR DESCRIPTION
**Pull request by marshall-levesque-nextgen**
After reinstalling jira-agile-metrics on a new Mac, I started seeing the error mentioned here: https://github.com/DeloitteDigitalUK/jira-agile-metrics/issues/30  None of the throughput charts were generating. 

@miohtama did a great job finding the source of the issue in a section of code that adds labels to the data points.  I think I fixed it with this PR.  Tested on my side and all throughput charts are generating again.

### CODE REVIEW

**Comment by marshall-levesque-nextgen** [comment]
@optilude  - great point on the tests.  Currently this failure shows up on master branch as well. 

I'll see if I can figure out the issue

**Comment by marshall-levesque-nextgen** [comment]
@optilude  - all tests passing. We have some assertions on list contents that can be flaky when order of elements in the list matters.

**Comment by vador** [comment]
Sorry if I sowed some confusion : removing toordinal makes it working perfectly for me (but the PR I looked at changed only one instance in throughtput, and there was another in progress metrics).

**Comment by marshall-levesque-nextgen** [comment]
If you can describe and create, or link to an issue we are facing with test cases I can take a look.

**Comment by vador** [comment]
Once again, I'm sorry, I just wanted to say that PR #44 (this one) and PR https://github.com/DeloitteDigitalUK/jira-agile-metrics/pull/45 are correcting failures in throughput and progress respectively.
So everything is fine from my side.

**Pull request merged**
